### ISSUE TITLE
PhantomJS not found

### ISSUE THREAD

**Issue by arnfinn** [Helseatlas/docker-shinymap#1]
Running `devtools::test("shinymap")` gives the following error:

```
test_app.R:6: error: app gets expected output
PhantomJS not found.
```

Not sure why, since the following is in the docker file:

```
RUN R -e "shinytest::installDependencies()"
```

If I run `shinytest::installDependencies()`, then everything is OK.

**Comment by areedv** [comment]
PhantomJS executable is now available in the R search path (PATH environ var), please test

**Comment by arnfinn** [comment]
Working fine after running `docker pull hnskde/shinymap`
